spring.application.name=insights
server.port=9201

# --- COMMENT OUT MYSQL ---
# spring.datasource.url=jdbc:mysql://localhost:3306/insight
# spring.datasource.username=root
# spring.datasource.password=Root@12345

# --- ADD POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/insight
spring.datasource.username=Root@12345
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate logic
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile