# ===============================
# APPLICATION
# ===============================
spring.application.name=generator
server.port=9021

# ===============================
# GEMINI API
# ===============================
spring.ai.google.genai.api-key=AIzaSyCD_s4RnIKZIdA3DcgFfkloML7-Cj98yHY
spring.ai.google.genai.chat.api-key=AIzaSyCD_s4RnIKZIdA3DcgFfkloML7-Cj98yHY
spring.ai.google.genai.embedding.api-key=AIzaSyCD_s4RnIKZIdA3DcgFfkloML7-Cj98yHY
gemini.api.key=AIzaSyCD_s4RnIKZIdA3DcgFfkloML7-Cj98yHY

# ===============================
# MODEL CONFIG
# ===============================
spring.ai.google.genai.embedding.options.model=text-embedding-001
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview

# ===============================
# VECTOR STORE
# ===============================
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/insight
spring.datasource.username=root
spring.datasource.password=Root@12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# DOCKER
# ===============================
spring.docker.compose.lifecycle-management=start_only

# ===============================
# DEBUG
# ===============================
logging.level.org.springframework.web=INFO
logging.level.org.springframework.jdbc=INFO
logging.level.org.hibernate.SQL=INFO