spring.application.name=insights
server.port=9201

# --- COMMENT OUT MYSQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/insight
spring.datasource.username=root
spring.datasource.password=Root@12345

# --- ADD POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/insight
spring.datasource.username=root
spring.datasource.password=Root@12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate logic
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- API Keys (SECURED VIA ENV VARIABLES) ---
# Set these in your IDE environment variables as GEMINI_API_KEY
spring.ai.google.genai.api-key=AIzaSyAG0xXV-COZz2osER6boZPY3DyvRaqmcP4
spring.ai.google.genai.chat.api-key=AIzaSyAG0xXV-COZz2osER6boZPY3DyvRaqmcP4
spring.ai.google.genai.embedding.api-key=AIzaSyAG0xXV-COZz2osER6boZPY3DyvRaqmcP4
gemini.api.key=AIzaSyAG0xXV-COZz2osER6boZPY3DyvRaqmcP4

# --- Gemini Model Configuration ---
spring.ai.google.genai.embedding.options.model=text-embedding-001
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview
spring.ai.google.genai.project-id=unused
spring.ai.google.genai.embedding.options.output-dimensionality=768
#swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method